AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'local/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'target/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - 'locale/translations.rb'
    - 'lib/scratch.rb'

  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_fail

Style/ConditionalAssignment:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/AbcSize:
  Enabled: False

Metrics/CyclomaticComplexity:
  Enabled: False

Metrics/PerceivedComplexity:
  Enabled: False

Metrics/LineLength:
  Max: 160

Metrics/BlockNesting:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact